weird <- c("Sweden", "Norway", "Finland", "United Kingdom", "Ireland", "Spain",
           "Portugal", "France", "Italy", "Switzerland", "Austria", "Germany",
           "Slovakia", "Hungary", "Czech Republic", "Poland", "Croatia", "Slovenia", 
           "Netherlands","Belgium", "Luxembourg","Liechtenstein", "Vatican", "Andorra",
           "Monaco", "Denmark", "Latvia", "Lithuania", "Estonia", "Iceland", "New Zealand", 
           "Australia", "United States", "Canada", "Israel")# "Uruguay", "Argentina", "Chile", "Japan", "South Korea", "South Africa")

countries <- c("Afghanistan", "Albania", "Algeria", "Argentina", "Armenia", "Australia", "Brunei",
              "Austria", "Azerbaijan", "Bahrain", "Bangladesh", "Belarus", "Belgium", "Angola", "Somalia",
              "Benin", "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Burundi",
              "Bulgaria", "Burkina Faso", "Cambodia", "Cameroon", "Canada", "Comoros", "Bhutan",
              "Central African Republic", "Chad", "Chile", "China", "Colombia", "Cape Verde",
              "Congo, Dem. Rep.", "Congo, Rep.", "Costa Rica", "Côte d'Ivoire", "East Timor",
              "Croatia", "Cyprus", "Czech Republic", "Denmark", "Dominican Republic", "Fiji",
              "Ecuador", "Egypt, Arab Rep.", "El Salvador", "Estonia", "Ethiopia","Eritrea" , "Finland", "Gambia",
              "France", "Gabon", "Georgia", "Germany", "Ghana", "Greece", "Guatemala", "Guinea", "Guinea Bissau", "Papua New Guinea",
              "Haiti", "Honduras", "Hong Kong SAR, China", "Hungary", "India", "Indonesia",  "Guam",
              "Iran, Islamic Rep.", "Iraq", "Ireland", "Israel", "Italy", "Japan", "Jordan",
              "Kazakhstan", "Kenya", "Korea, Rep.", "Kosovo", "Kuwait", "Kyrgyz Republic", "Laos",
              "Lao PDR", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Lithuania", "Syrian Arab Republic",  
              "Luxembourg", "Macedonia, FYR", "Madagascar", "Malawi", "Malaysia", "Mali", "Micronesia, Fed. States Of",
              "Malta", "Mauritania", "Mauritius", "Mexico", "Moldova", "Mongolia", "Montenegro", 
              "Morocco", "Mozambique", "Myanmar", "Namibia", "Nepal", "Netherlands", "New Zealand", "Oman",
              "Nicaragua", "Niger", "Nigeria", "Norway", "Pakistan", "Panama", "Paraguay", "Peru",
              "Philippines", "Poland", "Portugal", "Romania", "Russian Federation", "Rwanda", "Papua New Guinea",
              "Saudi Arabia", "Senegal", "Serbia", "Sierra Leone", "Singapore", "Slovak Republic", "Northern Cyprus",
              "Slovenia", "South Africa", "South Sudan", "Sudan", "Spain", "Sri Lanka", "Sweden","Swaziland",
              "Switzerland", "Tajikistan", "Tanzania", "Thailand", "Togo", "Taiwan", "Solomon Islands", "New Caledonia",
              "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Uganda", "Sao Tome And Principe", "Northern Mariana Islands",
              "Ukraine", "United Arab Emirates", "United Kingdom", "United States", "Uruguay", "Seychelles",
              "Uzbekistan", "Venezuela, RB", "Vietnam", "West Bank and Gaza", "Yemen, Rep.", "Zambia", "Nauru", "Vanuatu",
              "Zimbabwe")

nonweird <- countries[!(countries %in% weird)]
