weird <- c("Sweden", "Norway", "Finland", "United Kingdom", "Ireland", "Spain",
           "Portugal", "France", "Italy", "Switzerland", "Austria", "Germany",
           "Slovakia", "Hungary", "Czech Republic", "Poland", "Croatia", "Slovenia", 
           "Netherlands","Belgium", "Luxembourg","Liechtenstein", "Vatican", "Andorra",
           "Monaco", "Denmark", "Latvia", "Lithuania", "Estonia", "Iceland", "New Zealand", 
           "Australia", "United States", "Canada", "Israel")# "Uruguay", "Argentina", "Chile", "Japan", "South Korea", "South Africa")

countries <- c("Afghanistan", "Albania", "Algeria", "Argentina", "Armenia", "Australia",
              "Austria", "Azerbaijan", "Bahrain", "Bangladesh", "Belarus", "Belgium", 
              "Benin", "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", 
              "Bulgaria", "Burkina Faso", "Cambodia", "Cameroon", "Canada",
              "Central African Republic", "Chad", "Chile", "China", "Colombia",
              "Congo, Dem. Rep.", "Congo, Rep.", "Costa Rica", "Côte d'Ivoire", 
              "Croatia", "Cyprus", "Czech Republic", "Denmark", "Dominican Republic", 
              "Ecuador", "Egypt, Arab Rep.", "El Salvador", "Estonia", "Ethiopia", "Finland",
              "France", "Gabon", "Georgia", "Germany", "Ghana", "Greece", "Guatemala", "Guinea", 
              "Haiti", "Honduras", "Hong Kong SAR, China", "Hungary", "India", "Indonesia", 
              "Iran, Islamic Rep.", "Iraq", "Ireland", "Israel", "Italy", "Japan", "Jordan",
              "Kazakhstan", "Kenya", "Korea, Rep.", "Kosovo", "Kuwait", "Kyrgyz Republic", 
              "Lao PDR", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Lithuania", 
              "Luxembourg", "Macedonia, FYR", "Madagascar", "Malawi", "Malaysia", "Mali", 
              "Malta", "Mauritania", "Mauritius", "Mexico", "Moldova", "Mongolia", "Montenegro", 
              "Morocco", "Mozambique", "Myanmar", "Namibia", "Nepal", "Netherlands", "New Zealand",
              "Nicaragua", "Niger", "Nigeria", "Norway", "Pakistan", "Panama", "Paraguay", "Peru",
              "Philippines", "Poland", "Portugal", "Romania", "Russian Federation", "Rwanda", 
              "Saudi Arabia", "Senegal", "Serbia", "Sierra Leone", "Singapore", "Slovak Republic", 
              "Slovenia", "South Africa", "South Sudan", "Spain", "Sri Lanka", "Sweden",
              "Switzerland", "Tajikistan", "Tanzania", "Thailand", "Togo",
              "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Uganda", 
              "Ukraine", "United Arab Emirates", "United Kingdom", "United States", "Uruguay", 
              "Uzbekistan", "Venezuela, RB", "Vietnam", "West Bank and Gaza", "Zambia",
              "Zimbabwe")

nonweird <- countries[!(countries %in% weird)]
